{"uuid":"acfce9c4-8170-4093-8b10-fb7f5990ce3c","historyId":"935d93ade5898e6ae1ef573105500c3","fullName":"tests.CertificateValidationTest.testExpiredCertificate","labels":[{"name":"package","value":"tests.CertificateValidationTest"},{"name":"testClass","value":"tests.CertificateValidationTest"},{"name":"testMethod","value":"testExpiredCertificate"},{"name":"parentSuite","value":"Default Suite"},{"name":"suite","value":"Frameowork"},{"name":"subSuite","value":"tests.CertificateValidationTest"},{"name":"host","value":"GHYP2H2XFJ"},{"name":"thread","value":"22854@GHYP2H2XFJ.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"},{"name":"story","value":"Expired Certificate Validation"},{"name":"severity","value":"critical"}],"links":[],"name":"testExpiredCertificate","status":"failed","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"Expected CertificateExpiredException, but no exception was thrown","trace":"java.lang.AssertionError: Expected CertificateExpiredException, but no exception was thrown\n\tat org.testng.Assert.fail(Assert.java:110)\n\tat tests.CertificateValidationTest.testExpiredCertificate(CertificateValidationTest.java:65)\n\tat java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:580)\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)\n\tat org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)\n\tat org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)\n\tat org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)\n\tat org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)\n\tat org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1597)\n\tat org.testng.TestRunner.privateRun(TestRunner.java:829)\n\tat org.testng.TestRunner.run(TestRunner.java:602)\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:437)\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:330)\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1176)\n\tat org.testng.TestNG.runSuites(TestNG.java:1099)\n\tat org.testng.TestNG.run(TestNG.java:1067)\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)\n"},"stage":"finished","description":"Verify an expired certificate is detected and validation fails","steps":[],"attachments":[],"parameters":[],"start":1742541211157,"stop":1742541211170}